language: python

install:
  - pip install transifex-client

script:
  - echo "Run something"

deploy:
  - provider: script
    script: ./txpush.sh
    on:
      branch: devel

  - provider: script
    script: ./txpull.sh
    on:
      tags: true